Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    Option     "HWCursor" "True"
    VendorName     "NVIDIA Corporation"
    BoardName      "NVIDIA RTX A2000 Laptop GPU"
    Option         "TripleBuffer" "On"
    Option         "ConnectToAcpid" "On"
    # Cambiamos a FULL para mejor estabilidad en 4K + 1440p
    Option         "ForceFullCompositionPipeline" "On"
    Option         "AllowIndirectGLXProtocol" "off"
    # Desbloquea Overclock y control manual de ventiladores
    Option         "Coolbits" "24"
    # PowerMizer: Nivel 0x1 en AC es "Prefer Maximum Performance"
    Option         "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerDefaultAC=0x1"
EndSection
