#################################
#           Animations          #
#################################

animations = ({
    triggers = ["open", "show"];
    preset = "appear";
    duration = 0.1;
    scale = 0.9;
},{
    triggers = ["close", "hide"];
    preset = "disappear";
    duration = 0.1;
    scale = 0.9;
},{
    triggers = ["geometry"];
    preset = "geometry-change";
    duration = 0.2;
});

# fading = true
# fade-in-step = 0.06;
# fade-out-step = 0.06;


#################################
#     Background-Blurring       #
#################################

blur: {
  method = "dual_kawase";
  strength = 12;
  background = false;
  background-frame = false;
  background-fixed = true;
}

blur-background-exclude = [
  "class_g = 'Chromium'"
];

# to make vs code and discord a bit transparent and blurred
opacity-rule = [
    "90:class_g = 'Code'",
    "90:class_g = 'kitty'",
    "90:class_g = 'goland'",
    "80:class_g = 'tidal-hifi'",
    "88:class_g = 'discord'",
]


#################################
#           Corners             #
#################################

corner-radius = 0


#################################
#       General Settings        #
#################################

backend = "glx"

vsync = true

detect-rounded-corners = true;

detect-transient = true;

